module.exports.descriptors = [
    "Zilais",
    "Sarkanais",
    "Akmeņainais",
    "Dunošais",
    "Krāčainais",
    "Krītošais",
    "Klusais",
    "Priežu",
    "Varžu",
    "Kļavu",
    "Miglainais",
    "Aļņu",
    "Lāču",
    "Jūras",
    "Ezera",
    "Debesu",
    "Smilšainais",
    "Dzintara",
    "Zaļais",
    "Purva",
];

module.exports.places = [
    "Kalns",
    "Ciems",
    "Grava",
    "Dīķis",
    "Nometne",
    "Zirgu Aploks",
    "Vecciems",
    "Apmetne",
    "Meža Biezoknis",
    "Mežonīgā Daba",
    "Upe",
    "Strauts",
    "Upes Krasts",
    "Līcis",
    "Avots",
    "Piekraste",
    "Smiltāji",
    "Ganības",
    "Medību Teritorija",
    "Klintis",
    "Ieleja",
    "Purvājs",
    "Pļava",
    "Mežs",
];
