module.exports.descriptors = [
    "Zilais",
    "Sarkanais",
    "Akmeņainais",
    "Krītošais",
    "Klusais",
    "Priežu",
    "Varžu",
    "Kļavu",
    "Miglainais",
    "Aļņu",
    "Lāču",
    "Jūras",
    "Ezera",
    "Debesu",
    "Smilšainais",
    "Dzintara",
    "Zaļais",
];

module.exports.places = [
    "Kalns",
    "Ciems",
    "Dīķis",
    "Nometne",
    "Zirgu Aploks",
    "Vecciems",
    "Apmetne",
    "Meža Biezoknis",
    "Strauts",
    "Upes Krasts",
    "Līcis",
    "Avots",
    "Smiltājs",
    "Purvājs",
    "Mežs",
    "Purvs",
    "Dūriņš",
];
